# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('prefix', models.CharField(choices=[('mr', 'Mr.'), ('dr', 'Dr.'), ('ms', 'Mrs.'), ('mi', 'Miss')], default='dr', help_text="Prefix for the user's name.", max_length=2)),
                ('first_name', models.CharField(default='', help_text="The user's first name.", max_length=128)),
                ('last_name', models.CharField(default='', help_text="The user's last name.", max_length=128)),
                ('type', models.CharField(choices=[('co', 'Venture Coach'), ('us', 'User')], default='us', help_text='Account type.', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Checkup', max_length=64)),
                ('minutes', models.IntegerField(default=45, help_text='Amount of time in minutes for the appointment.')),
            ],
            options={
                'db_table': 'appt_types',
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Vacation', max_length=32)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'exceptions',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='UserAppointmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_start', models.TimeField(default=django.utils.timezone.now)),
                ('sun_end', models.TimeField(default=django.utils.timezone.now)),
                ('mon_start', models.TimeField(default=django.utils.timezone.now)),
                ('mon_end', models.TimeField(default=django.utils.timezone.now)),
                ('tue_start', models.TimeField(default=django.utils.timezone.now)),
                ('tue_end', models.TimeField(default=django.utils.timezone.now)),
                ('wed_start', models.TimeField(default=django.utils.timezone.now)),
                ('wed_end', models.TimeField(default=django.utils.timezone.now)),
                ('thu_start', models.TimeField(default=django.utils.timezone.now)),
                ('thu_end', models.TimeField(default=django.utils.timezone.now)),
                ('fri_start', models.TimeField(default=django.utils.timezone.now)),
                ('fri_end', models.TimeField(default=django.utils.timezone.now)),
                ('sat_start', models.TimeField(default=django.utils.timezone.now)),
                ('sat_end', models.TimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appt_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_appointment_managers',
            },
        ),
        migrations.AddField(
            model_name='timeoff',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='appointments.UserAppointmentManager'),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appt_types', to='appointments.UserAppointmentManager'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.UserAppointmentManager'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.AppointmentType'),
        ),
    ]
